export const ApiRoutes = {
    RegisterBuyer: 'auth/register/',
    RegisterVendor: 'vendor/register/signup/',
    LoginBuyer: 'auth/login/',
    VerifyEmail: 'auth/verify-email/',
    VerifyVendorEmail: 'vendor/register/verify-email/',
    CreatePassword: 'vendor/register/create-password/',
    SetupBusinessAcccount: 'vendor/register/setup-account/',
    ResendVerifyEmail: 'auth/resend-verification-code/',
    SocialAuthURL: 'auth/social/auth-url/',
    GetSocialCallBack: 'auth/social/callback/',
    RefreshToken: "auth/token/refresh/",
    InitiateResetPassword: 'auth/password-reset/',
    ValidatePasswordToken: 'auth/password-reset/validate-token/',
    ResetPassword: 'auth/password-reset/confirm/',
    GetAllProducts: 'products/list/',
    GetCategory: 'products/categories/',
    GetSignedURL: 'misc/cloudinary/get-signed-url/',
    AddProduct: 'products/add/',
    SingleProduct: 'products',
    AddToCart: 'orders/cart/add/',
    GetUserCart: 'orders/cart/',
    ClearCart:  'orders/cart/clear/',
    AddReview: 'products',
    GetAllReviews: 'products/reviews/',
    GetSellersReview: 'products/seller/reviews/',
    GetUserProfile: 'user/profile/'
}